Capa_Presentacion/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Capa_Enitdad;
using Capa_Negocio;

namespace Capa_Presentacion.Controllers
{
    public class CategoriesController : Controller
    {
        CategoriesBusiness Business = new CategoriesBusiness();
        // GET: Categories
        public ActionResult Index()
        {      
            return View(Business.show());
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "categoryName,categoryDescription")] Categories categories)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Business.Insert(categories);
                    return RedirectToAction("Index");
                }

                return View(categories);
            }
            catch (Exception e)
            {
                return View(e.Message);
            }
           
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                if (Business.Edit(id) == null)
                {
                    return HttpNotFound();
                }
                return View(Business.Edit(id));
            }
            catch (Exception e)
            {
                return View(e.Message);
            }
        }

        // POST: Categories/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "categoryId,categoryName,categoryDescription")] Categories categories)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Business.Update(categories);
                    return RedirectToAction("Index");
                }
                return View(categories);
            }
            catch (Exception e)
            {
                return View(e.Message);
            }
        }

        // GET: Categories/Delete/5
        public ActionResult delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (Business.deleteId(id) == null)
            {
                return HttpNotFound();
            }
            return View(Business.deleteId(id));
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                Business.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {

                return View(e.Message);
            }
        }
    }
}

Capa_Presentacion/Views/Categories/Create.cshtml
@model Capa_Enitdad.Categories

@{
    ViewBag.Title = "Create";
}

@section styles{
    <link rel="stylesheet" href="~/Content/stylesFormularios.css" type="text/css"/>

}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Categories", FormMethod.Post, new { id = "formCategories" }))
{
    @Html.AntiForgeryToken()
    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
    <div class="form-horizontal">
        <h4>Categories</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.categoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoryDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/custom-validator")

}

Capa_Presentacion/Views/Categories/Edit.cshtml
@model Capa_Enitdad.Categories

@{
    ViewBag.Title = "Edit";
}

@section styles{
    <link rel="stylesheet" href="~/Content/stylesFormularios.css" type="text/css" />

}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Categories", FormMethod.Post, new { id = "formCategories" }))
{
    @Html.AntiForgeryToken()
    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
    <div class="form-horizontal">
        <h4>Categories</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.categoryId);

        <div class="form-group">
            @Html.LabelForModel("Category Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelForModel("Category Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/custom-validator")

}

Capa_Presentacion/Views/Categories/Index.cshtml
@model IEnumerable<Capa_Enitdad.Categories>

@{
    ViewBag.Title = "Index";
}

@section styles{
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />

}

<h2>List of Categories</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table" id="tabledemo">
    <thead>
        <tr>
            <th>
                @Html.LabelForModel("Category Id")
            </th>
            <th>
                @Html.LabelForModel("Category Name")
            </th>
            <th>
                @Html.LabelForModel("Category Description")
            </th>
            @if (User.Identity.IsAuthenticated)
            {
                <th>@Html.LabelForModel("Action")</th>
            }

        </tr>
    <thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.categoryId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.categoryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.categoryDescription)
                </td>
                @{
                    if (User.Identity.IsAuthenticated)
                    {
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.categoryId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.categoryId })
                        </td>
                    }
                }

            </tr>
        }
    </tbody>
</table>


@section scripts{
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

    <script>
        $('.table').DataTable({
            "paging": true,
            "ordering": true,
            "info": true,

            "language": {
                "lengthMenu": "showing  _MENU_ records",
                "zeroRecords": "Not found - Sorry",
                "info": "Showing page _PAGE_ de _PAGES_",
                "infoEmpty": "No records available",
                "infoFiltered": "(filtrado de _MAX_  total records)",
                "search": "Search",
                "next": "After",
                "previous": "Previous",

            }
        });
    </script>
}

Capa_Presentacion/Views/Categories/delete.cshtml
@model Capa_Enitdad.Categories

@{
    ViewBag.Title = "delete";
}

<h2>delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Categories</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.LabelForModel("Category Id")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryId)
        </dd>

        <dt>
            @Html.LabelForModel("Category Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryName)
        </dd>

        <dt>
            @Html.LabelForModel("Category Description")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>